name: 'Publish new release 🚀'

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: myparcelnl/actions/setup-git-credentials@v5
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: ./.github/actions/setup

      - uses: myparcelnl/actions/semantic-release@v5
        with:
          token: ${{ steps.credentials.outputs.token }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
