name: 'Publish new release 🚀'

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GH_REPO_TOKEN }}

      # TODO: Switch to v3 with app credentials when GitHub apps are allowed to bypass status checks. https://github.com/orgs/community/discussions/43460
      - uses: myparcelnl/actions/setup-git-credentials@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: ./.github/actions/setup

      - uses: myparcelnl/actions/semantic-release@v3
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
