name: 'Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16, 18, 20 ]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Run tests'
        shell: bash
        run: yarn test:coverage

      - uses: codecov/codecov-action@v3
        if: matrix.node-version == vars.NODE_VERSION
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: 'Run publint'
        if: matrix.node-version == vars.NODE_VERSION
        shell: bash
        run: npx -q publint
