name: 'Run tests 🧪'

on:
  workflow_call:

  pull_request:
    branches:
      - main

  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 14, 16, 18, 20 ]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Run tests'
        shell: bash
        run: yarn test:coverage

      - uses: codecov/codecov-action@v3
        if: matrix.node-version == vars.NODE_VERSION
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: codacy/codacy-coverage-reporter-action@v1
        if: matrix.node-version == vars.NODE_VERSION
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}

      - name: 'Run publint'
        if: matrix.node-version == vars.NODE_VERSION
        shell: bash
        run: npx -q publint
